### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by expcapitaldev** [ionic-team/cordova-plugin-ionic-keyboard#60]
App sometimes crashes.

0 | java.lang.NullPointerException:  'android.view.View android.view.View.getRootView()' on a null object reference
-- | --
1 | at io.ionic.keyboard.IonicKeyboard$3.run(IonicKeyboard.java:69)
2 | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
3 | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
4 | at java.lang.Thread.run(Thread.java:764)

**Comment by ankit18singh** [comment]
@expcapitaldev Hi, did you find any solution for this issue?

**Comment by jcesarmobile** [comment]
would help if you could provide a sample app where it crash, I have never seen it crash there.
